# encoding: UTF-8

Category.find_or_create_by_title('Домакинска работа')
Category.find_or_create_by_title('Монтажни')
Category.find_or_create_by_title('Хамалски')
Category.find_or_create_by_title('Ремонт')
Category.find_or_create_by_title('Транспорт')
Category.find_or_create_by_title('Пазаруване')
Category.find_or_create_by_title('Промотиране')
Category.find_or_create_by_title('Дом. любимци')
Category.find_or_create_by_title('Градина')
Category.find_or_create_by_title('Козметични')
Category.find_or_create_by_title('Писане')
Category.find_or_create_by_title('Преводи')

state_blg = State.find_or_create_by_name('Благоевград')
state_bs =  State.find_or_create_by_name('Бургас')
state_var = State.find_or_create_by_name('Варна')
state_vt =  State.find_or_create_by_name('Велико Търново')
state_vid = State.find_or_create_by_name('Видин')
state_vra = State.find_or_create_by_name('Враца ')
state_gab = State.find_or_create_by_name('Габрово')
state_dob = State.find_or_create_by_name('Добрич')
state_kur = State.find_or_create_by_name('Кърджали')
state_kus = State.find_or_create_by_name('Кюстендил')
state_lov = State.find_or_create_by_name('Ловеч')
state_mon = State.find_or_create_by_name('Монтана')
state_paz = State.find_or_create_by_name('Пазарджик')
state_ple = State.find_or_create_by_name('Плевен')
state_per = State.find_or_create_by_name('Перник')
state_plo = State.find_or_create_by_name('Пловдив')
state_raz = State.find_or_create_by_name('Разград')
state_rus = State.find_or_create_by_name('Русе')
state_sil = State.find_or_create_by_name('Силистра')
state_sli = State.find_or_create_by_name('Сливен')
state_smo = State.find_or_create_by_name('Смолян')
state_sf =  State.find_or_create_by_name('София - град')
state_so =  State.find_or_create_by_name('София - област')
state_stz = State.find_or_create_by_name('Стара Загора')
state_tur = State.find_or_create_by_name('Търговище')
state_has = State.find_or_create_by_name('Хасково')
state_shu = State.find_or_create_by_name('Шумен')
state_yam = State.find_or_create_by_name('Ямбол')

City.find_or_create_by_name_and_state_id(name: 'Айтос', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Аксаково', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Алфатар', state_id: state_sil.id)
City.find_or_create_by_name_and_state_id(name: 'Антоново', state_id: state_tur.id)
City.find_or_create_by_name_and_state_id(name: 'Априлци', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Ардино', state_id: state_kur.id)
City.find_or_create_by_name_and_state_id(name: 'Асеновград', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Ахелой', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Ахтопол', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Балчик', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Банкя', state_id: state_sf.id)
City.find_or_create_by_name_and_state_id(name: 'Банско', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Баня', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Батак', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Батановци', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Белене', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Белица', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Белово', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Белоградчик', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Белослав', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Берковица', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Благоевград', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Бобов дол', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Бобошево', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Божурище', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Бойчиновци', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Болярово', state_id: state_yam.id)
City.find_or_create_by_name_and_state_id(name: 'Борово', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Ботевград', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Брацигово', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Брегово', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Брезник', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Брезово', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Брусарци', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Бургас', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Бухово', state_id: state_sf.id)
City.find_or_create_by_name_and_state_id(name: 'Българово', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Бяла (Варна)', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Бяла (Русе)', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Бяла Слатина', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Бяла Черква', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Варна', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Велики Преслав', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Велико Търново', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Велинград', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Ветово', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Ветрен', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Видин', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Враца', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Вълчедръм', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Вълчи дол', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Върбица', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Вършец', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Габрово', state_id: state_gab.id)
City.find_or_create_by_name_and_state_id(name: 'Генерал Тошево', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Главиница', state_id: state_sil.id)
City.find_or_create_by_name_and_state_id(name: 'Глоджево', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Годеч', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Горна Оряховица', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Гоце Делчев', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Грамада', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Гулянци', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Гурково', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Гълъбово', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Две могили', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Дебелец', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Девин', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Девня', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Джебел', state_id: state_kur.id)
City.find_or_create_by_name_and_state_id(name: 'Димитровград', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Димово', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Добринище', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Добрич', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Долна баня', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Долна Митрополия', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Долна Оряховица', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Долни Дъбник', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Долни чифлик', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Доспат', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Драгоман', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Дряново', state_id: state_gab.id)
City.find_or_create_by_name_and_state_id(name: 'Дулово', state_id: state_sil.id)
City.find_or_create_by_name_and_state_id(name: 'Дунавци', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Дупница', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Дългопол', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Елена', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Елин Пелин', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Елхово', state_id: state_yam.id)
City.find_or_create_by_name_and_state_id(name: 'Етрополе', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Завет', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Земен', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Златарица', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Златица', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Златоград', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Ивайловград', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Игнатиево', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Искър', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Исперих', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Ихтиман', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Каблешково', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Каварна', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Казанлък', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Калофер', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Камено', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Каолиново', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Карлово', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Карнобат', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Каспичан', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Кермен', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Килифарево', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Китен', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Клисура', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Кнежа', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Козлодуй', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Койнаре', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Копривщица', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Костандово', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Костенец', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Костинброд', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Котел', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Кочериново', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Кресна', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Криводол', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Кричим', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Крумовград', state_id: state_kur.id)
City.find_or_create_by_name_and_state_id(name: 'Кубрат', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Куклен', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Кула', state_id: state_vid.id)
City.find_or_create_by_name_and_state_id(name: 'Кърджали', state_id: state_kur.id)
City.find_or_create_by_name_and_state_id(name: 'Кюстендил', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Левски', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Летница', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Ловеч', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Лозница', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Лом', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Луковит', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Лъки', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Любимец', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Лясковец', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Мадан', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Маджарово', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Малко Търново', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Мартен', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Мездра', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Мелник', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Меричлери', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Мизия', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Момин проход', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Момчилград', state_id: state_kur.id)
City.find_or_create_by_name_and_state_id(name: 'Монтана', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Мъглиж', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Неделино', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Несебър', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Николаево', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Никопол', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Нова Загора', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Нови Искър', state_id: state_sf.id)
City.find_or_create_by_name_and_state_id(name: 'Нови пазар', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Обзор', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Омуртаг', state_id: state_tur.id)
City.find_or_create_by_name_and_state_id(name: 'Опака', state_id: state_tur.id)
City.find_or_create_by_name_and_state_id(name: 'Оряхово', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Павел баня', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Павликени', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Пазарджик', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Панагюрище', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Перник', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Перущица', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Петрич', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Пещера', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Пирдоп', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Плачковци', state_id: state_gab.id)
City.find_or_create_by_name_and_state_id(name: 'Плевен', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Плиска', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Пловдив', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Полски Тръмбеш', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Поморие', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Попово', state_id: state_tur.id)
City.find_or_create_by_name_and_state_id(name: 'Пордим', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Правец', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Приморско', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Провадия', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Първомай', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Раднево', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Радомир', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Разград', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Разлог', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Ракитово', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Раковски', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Рила', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Роман', state_id: state_vra.id)
City.find_or_create_by_name_and_state_id(name: 'Рудозем', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Русе', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Садово', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Самоков', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Сандански', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Сапарева баня', state_id: state_kus.id)
City.find_or_create_by_name_and_state_id(name: 'Свети Влас', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Свиленград', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Свищов', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Своге', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Севлиево', state_id: state_gab.id)
City.find_or_create_by_name_and_state_id(name: 'Сеново', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Септември', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Силистра', state_id: state_sil.id)
City.find_or_create_by_name_and_state_id(name: 'Симеоновград', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Симитли', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Славяново', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Сливен', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Сливница', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Сливо поле', state_id: state_rus.id)
City.find_or_create_by_name_and_state_id(name: 'Смолян', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Смядово', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Созопол', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Сопот', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'София', state_id: state_sf.id)
City.find_or_create_by_name_and_state_id(name: 'Средец', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Стамболийски', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Стара Загора', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Стражица', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Стралджа', state_id: state_yam.id)
City.find_or_create_by_name_and_state_id(name: 'Стрелча', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Суворово', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Сунгурларе', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Сухиндол', state_id: state_vt.id)
City.find_or_create_by_name_and_state_id(name: 'Съединение', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Сърница', state_id: state_paz.id)
City.find_or_create_by_name_and_state_id(name: 'Твърдица', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Тервел', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Тетевен', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Тополовград', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Троян', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Трън', state_id: state_per.id)
City.find_or_create_by_name_and_state_id(name: 'Тръстеник', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Трявна', state_id: state_gab.id)
City.find_or_create_by_name_and_state_id(name: 'Тутракан', state_id: state_sil.id)
City.find_or_create_by_name_and_state_id(name: 'Търговище', state_id: state_tur.id)
City.find_or_create_by_name_and_state_id(name: 'Угърчин', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Хаджидимово', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Харманли', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Хасково', state_id: state_has.id)
City.find_or_create_by_name_and_state_id(name: 'Хисаря', state_id: state_plo.id)
City.find_or_create_by_name_and_state_id(name: 'Цар Калоян', state_id: state_raz.id)
City.find_or_create_by_name_and_state_id(name: 'Царево', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Чепеларе', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Червен бряг', state_id: state_ple.id)
City.find_or_create_by_name_and_state_id(name: 'Черноморец', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Чипровци', state_id: state_mon.id)
City.find_or_create_by_name_and_state_id(name: 'Чирпан', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Шабла', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Шивачево', state_id: state_sli.id)
City.find_or_create_by_name_and_state_id(name: 'Шипка', state_id: state_stz.id)
City.find_or_create_by_name_and_state_id(name: 'Шумен', state_id: state_shu.id)
City.find_or_create_by_name_and_state_id(name: 'Ябланица', state_id: state_lov.id)
City.find_or_create_by_name_and_state_id(name: 'Якоруда', state_id: state_blg.id)
City.find_or_create_by_name_and_state_id(name: 'Ямбол', state_id: state_yam.id)

City.find_or_create_by_name_and_state_id(name: 'Златни Пясъци', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Св. св. Константин и Елена', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Слънчев ден', state_id: state_var.id)
City.find_or_create_by_name_and_state_id(name: 'Албена', state_id: state_dob.id)
City.find_or_create_by_name_and_state_id(name: 'Боровец', state_id: state_so.id)
City.find_or_create_by_name_and_state_id(name: 'Дюни', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Елените', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Пампорово', state_id: state_smo.id)
City.find_or_create_by_name_and_state_id(name: 'Слънчев Бряг', state_id: state_bs.id)
City.find_or_create_by_name_and_state_id(name: 'Цигов Чарк', state_id: state_paz.id)
